AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'app/views/**/*.slim'
  TargetRubyVersion: 2.3
  DisplayCopNames: true

# Metrics Cops

Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - '**/*.jbuilder'
    - 'bin/*'
    - 'spec/**/*'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'config/sitemap.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

# Style Cops

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: False
Style/TrailingCommaInArguments:
  Enabled: False
Style/TrailingCommaInLiteral:
  Enabled: False
Style/SymbolArray:
  Enabled: false
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'
Style/FormatStringToken:
  Enabled: false
Style/PredicateName:
  Exclude:
    - 'spec/**/*_matchers.rb'
    - 'spec/**/*_spec.rb'

# Layout Cops
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

# Security Cops
Security/YAMLLoad:
  Exclude:
    - 'bin/*'

# Rails Cops
Rails:
  Enabled: true
Rails/TimeZone:
  EnforcedStyle: strict
