require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'app/views/**/*.slim'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable

# Metrics Cops

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - '**/*.jbuilder'
    - 'bin/*'
    - 'spec/**/*'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'config/sitemap.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

# Style Cops

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: False
Style/TrailingCommaInArguments:
  Enabled: False
Style/TrailingCommaInArrayLiteral:
  Enabled: False
Style/TrailingCommaInHashLiteral:
  Enabled: False
Style/SymbolArray:
  Enabled: false
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'
Style/FormatStringToken:
  Enabled: false
Style/SafeNavigation:
  Enabled: false

# Naming Cops
Naming/PredicateName:
  Exclude:
    - 'spec/**/*_matchers.rb'
    - 'spec/**/*_spec.rb'

# Layout Cops
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

# Security Cops
Security/YAMLLoad:
  Exclude:
    - 'bin/*'

# Rails Cops
Rails:
  Enabled: true
Rails/ContentTag:
  Enabled: false
Rails/TimeZone:
  EnforcedStyle: strict
