exclude:
  - 'vendor/**/*.slim'
linters:
  LineLength:
    max: 100
  RedundantDiv:
    enabled: false
  RuboCop:
    ignored_cops:
      - Layout/ArgumentAlignment
      - Layout/IndentationWidth
      - Layout/TrailingEmptyLines
      - Lint/Void
      - Style/FileName
      - Style/FrozenStringLiteralComment
