sudo: false
language: ruby
addons:
  postgresql: "9.6"
services:
  - postgresql
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bin/yarn
before_script:
  - psql -c 'create database niarevo_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake
