dist: trusty
sudo: false
language: ruby
addons:
  postgresql: "9.6"
services:
  - postgresql
cache:
  - bundler
  - yarn
before_script:
  - psql -c 'create database niarevo_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake
