--- 
javascripts: 
- base: 
  - jquery-1.3.2
  - jquery.boxy
  - jquery.form
  - shared
stylesheets: 
- base: 
  - blueprint/screen
  - boxy
  - moonset
- print:
  - blueprint/print
- ie:
  - blueprint/ie
