development:
  adapter: postgresql
  encoding: unicode
  database: niarevo_development
  pool: 5
  username: jason
  password:
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: niarevo_test
  pool: 5
  username: jason
  password:
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: niarevo_development
  pool: 5
  username: postgres
  password:
  min_messages: warning
