development:
  adapter: postgresql
  encoding: unicode
  database: niarevo_development
  pool: 5
  username: <%= ENV['POSTGRES_DEV_USER'] || 'postgres' %>
  password:
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: niarevo_test
  pool: 5
  username: <%= ENV['POSTGRES_DEV_USER'] || 'postgres' %>
  password:
  min_messages: warning
