default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  timeout: <%= ENV["DB_TIMEOUT"] || 5000 %>

development:
  <<: *default
  database: niarevo_development

test:
  <<: *default
  database: niarevo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
